name: zeni
description: "Zeni ajuda famílias a criarem hábitos com missões, mimos e estrelas."
publish_to: 'none'

version: 1.0.10+10

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  flutter_riverpod: ^3.3.1
  shared_preferences: ^2.5.5
  intl: ^0.20.2
  uuid: ^4.5.3
  crypto: ^3.0.6
  flutter_tts: ^4.2.5
  vibration: ^3.1.8
  flutter_local_notifications: ^21.0.0
  permission_handler: ^12.0.1
  supabase_flutter: ^2.12.4
  google_sign_in: ^7.2.0
  sign_in_with_apple: ^6.1.4
  local_auth: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/zeni_logo.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/

  fonts:
    - family: OpenDyslexic
      fonts:
        - asset: assets/fonts/opendislexy/OpenDyslexic-Regular.otf